buildChatService:
	go build -o bin/chatService cmd/chat/chatService.go

buildChatClient:
	go build -o bin/chatClient cmd/client/chatClient.go

buildChatServiceArgs:
	go build -o bin/chatServiceArgs cmd/args/chat/chatServiceArgs.go

buildChatClientArgs:
	go build -o bin/chatClientArgs cmd/args/client/chatClientArgs.go